### ISSUE TITLE
Exact quote details not carrying over to back end

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#71]
I generated a quote called cheese. The details came through on the email, apart from date which should have been 20th Oct but came through as 19th.
The details did not carry over into the back end, see images

**Comment by Pikapangokev** [comment]
![screen shot 2016-10-18 at 16 23 02](https://cloud.githubusercontent.com/assets/22468878/19484985/7ee96612-9551-11e6-9af4-83fe5ca032c1.png)
![screen shot 2016-10-18 at 16 23 51](https://cloud.githubusercontent.com/assets/22468878/19484991/8417a572-9551-11e6-855a-466fc2fe4ae2.png)
![screen shot 2016-10-18 at 16 24 00](https://cloud.githubusercontent.com/assets/22468878/19484999/88784554-9551-11e6-8bd3-b7ac3020c8ee.png)

**Comment by neilpie** [comment]
Testing #71
1500kg
Steve
07040118981
CT6 8TT (81)
2016-10-27
PM

*blank*
*blank*
CT6 8TT (91)


{
	"post_title": "Testing #71",
	"load_weight": "0-1500",
	"preferred_collect_date": "20161026",
	"preferred_collect_time": "PM",
	"collect_contact_name": "Steve",
	"collect_contact_phone": "07040118981",
	"collect_postcode": "CT6 8TT",
	"collect_address": "CT6 8TT, 81, Pier Avenue, Herne Bay ",
	"delivery_contact_name": "",
	"delivery_contact_phone": "",
	"delivery_postcode": "CT6 8TT",
	"delivery_address": "CT6 8TT, 91, Pier Avenue, Herne Bay "
}


RESP

JSONLint
The JSON Validator

Try PRO →

{
	"post_title": "Testing #71",
	"load_weight": "0-1500",
	"preferred_collect_date": "20161026",
	"preferred_collect_time": "PM",
	"collect_contact_name": "Steve",
	"collect_contact_phone": "07040118981",
	"collect_postcode": "CT6 8TT",
	"collect_address": "CT6 8TT, 81, Pier Avenue, Herne Bay ",
	"delivery_contact_name": "",
	"delivery_contact_phone": "",
	"delivery_postcode": "CT6 8TT",
	"delivery_address": "CT6 8TT, 91, Pier Avenue, Herne Bay "
}
1
{
2
    "ID": 1769,
3
    "post_author": "31",
4
    "post_date": "2016-10-26 11:12:29",
5
    "post_date_gmt": "2016-10-26 11:12:29",
6
    "post_content": "",
7
    "post_title": "Testing #71",
8
    "post_excerpt": "",
9
    "post_status": "publish",
10
    "comment_status": "closed",
11
    "ping_status": "closed",
12
    "post_password": "",
13
    "post_name": "testing-71",
14
    "to_ping": "",
15
    "pinged": "",
16
    "post_modified": "2016-10-26 11:12:29",
17
    "post_modified_gmt": "2016-10-26 11:12:29",
18
    "post_content_filtered": "",
19
    "post_parent": 0,
20
    "guid": "http:\/\/pikapango.staging.wpengine.com\/quote\/testing-71\/",
21
    "menu_order": 0,
22
    "post_type": "quote",
23
    "post_mime_type": "",
24
    "comment_count": "0",
25
    "filter": "raw",
26
    "meta": {
27
        "load_weight": ["0-1500"],
28
        "load_value": ["unknown"],
29
        "preferred_collect_time": ["PM"],
30
        "post_title": ["Testing #71"],
31
        "preferred_collect_date": ["20161026"],
Validate JSON  Clear
this is an AD →
Results

Valid JSON
Source is on GitHub. Props to Douglas Crockford of JSON and JS Lint and 
Zach Carter, who provided the pure JS implementation of jsonlint. FAQ Advertise
FAQ

What is JSONLint?

JSONLint is a validator and reformatter for JSON, a lightweight data-interchange format.

Why 'Lint'?

Essentially, I'm just riding on JSLint's coattails. The name 'lint' was originally used to find problems in C source files. It's not really valid here because JSON is just a protocol. Shameless? You bet!

Why does it reformat my JSON?

Because your code is ugly! Trust me on this one. What's that you say? It's not? Ok, well then here's JSON Lint without the reformatter.

Any secret features?

Sure, a few. You can input a URL and it'll scrape it for JSON and parse that.
An example URL to test: http://www.reddit.com/r/programming/comments/9szpc/jsonlint_a_handy_json_validator_and_reformatter.json

You can also provide JSON to lint in the URL if you link to JSON Lint with the "json" parameter of location hash. Here's an example URL to test.

Additionally, JSON Lint can also be used as a json compressor if you add #reformat=compress to the URL.

What are some common errors?

Expecting 'STRING'
You probably have an extra comma at the end of your collection. Something like: { "a": "b", }
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
You probably have an extra comma at the end of your list. Something like: [ "a", "b", ] 
You also may have not enclosed your collection keys in quotes. Proper format for a collection is: { "key": "value" }
Be sure to follow JSON's syntax properly. For example, always use double quotes, always quotify your keys, and remove all callback functions.

A friend and I pasted the same JSON in and got different results. Wat do?

If you and your friend are on different systems (Win/Unix), this is possible due to the way windows handles newlines. Essentially, if you have just newline characters (\n) in your JSON and paste it into JSONLint from a windows machine, it can validate it as valid erroneously since Windows may need a carriage return (\r) as well to detect newlines properly.

The solution: Either use direct URL input, or make sure your content's newlines match the architecture your system expects!

I've got feedback!

Great - hit us up on GitHub.

**Comment by neilpie** [comment]
@Pikapangokev the date issue and the Collect Time issue should now be OK
